'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import store from './Redux/Store/FavoritesStore';
import ThemeProvider from '@/theme/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <ThemeProvider>
        <Provider store={store}>
          <body className={inter.className}>{children}</body>
        </Provider>
      </ThemeProvider>
    </html>
  );
}
