'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import store from './Redux/Store/FavoritesStore';
import ThemeProvider from './theme/ThemeProvider';
import {
  ThemeContext,
  ThemeProviderContext,
} from './theme/ThemeProviderContext';
import { useContext } from 'react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { theme } = useContext(ThemeContext);

  return (
    <html lang='pt-br'>
      <ThemeProvider>
        <ThemeProviderContext>
          <Provider store={store}>
            <body className={inter.style.fontFamily}>{children}</body>
          </Provider>
        </ThemeProviderContext>
      </ThemeProvider>
    </html>
  );
}
